# Generated by Django 3.2 on 2022-03-14 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cat', models.CharField(max_length=30)),
                ('first_num', models.IntegerField(max_length=20)),
                ('balance_gr', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_prod', models.CharField(max_length=30)),
                ('inv_number', models.IntegerField(unique=True)),
                ('start_price', models.IntegerField()),
                ('rem_price', models.IntegerField()),
                ('category_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.category')),
            ],
        ),
    ]
